version: '3.9'
services:
  postgres:
    container_name: spbank_postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
  redis:
    container_name: spbank_redis
    image: redis:latest
    ports:
      - "6380:6379"
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:123456@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]